
# ./.github/workflows/dockerimage.yml

name: alphine

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # may be actions/checkout@v2 now
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag padalasurendra2428/work:al        #work:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push padalasurendra2428/work:al    # pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
